global:
  scrape_interval: 15s
  external_labels:
    monitor: 'prometheus'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['172.31.0.119:9090','172.31.0.217:9100','172.31.0.12:9100','172.31.0.242:9100']
